### ISSUE TITLE
ResourceViewer_Wrap is too big?

### ISSUE THREAD

**Issue by jayenashar** [coviu/coviu-addons#1]
I'm working on an addon, and I've just added a resource, but for some reason the resource is the width of the screen, instead of subtracting the camera area.  You can see below `width: 100%`.  The text is centered in the element, but most of the element is off the screen.

![image](https://user-images.githubusercontent.com/1137152/91969543-98398480-ed59-11ea-9667-e075ee196560.png)

**Comment by jerry-coviu** [comment]
in view function, there's parameter `availableSpace` to get `width` and `height` of resource. 
e.g. 
```
view: (resource, cache, resourceMethods, documentSizeCb, position, availableSpace) => {
  return h('div', {
    style: {
      height: `${availableSpace.height}px`,
      width: `${availableSpace.width}px`
    }
  });
}
```

**Comment by jayenashar** [comment]
that's not related.  the resource is taking up too much space.  the screenshot above is just a div with no styling.

**Comment by jayenashar** [comment]
oh the developer tools is missing.  here's a better screenshot
![image](https://user-images.githubusercontent.com/1137152/91975204-5f51dd80-ed62-11ea-8b1b-8caf8a1141e4.png)

**Comment by jerry-coviu** [comment]
Understood. Can you provide reproduction steps and environment information (e.g. version of browser)? We will look into it shortly.

**Comment by jayenashar** [comment]
i checked another resource (chart) and it seems you are right.  i have to limit the size within my own renderer.  that seems like extra work for every addon to do...

**Comment by jerry-coviu** [comment]
Glad to help you out. We will improve API interface for better ease of use. Thanks for your suggestion.
