### ISSUE TITLE
console should not kill CPU & network

### ISSUE THREAD

**Issue by jayenashar** [coviu/coviu-addons#20]
Happens in prod when logging large objects (e.g. video buffers).  Does not happen in dev.

**Comment by jerry-coviu** [comment]
Logging large video buffers occupied memory in the browser. It happened in dev as well

**Comment by jayenashar** [comment]
this was happening in prod only because rollbar was not enabled in dev.

**Comment by jayenashar** [comment]
console.log is fine but rollbar logging is the killer
